

#################################
######### Experiments 1 #########
#################################

Solution without constraint :
 

###### Memory Management #######
machine-25: (16)
machine-26: (32)
machine-28: (32)
machine-34: (16)
machine-35: (16)
machine-36: (16)
machine-39: (16)
machine-40: (8)
machine-49: (16)
machine-51: (16)
machine-52: (16)
machine-55: (16)
machine-56: (16)
machine-64: (16)
machine-73: (16)
machine-78: (16)
machine-80: (32)
machine-90: (16)
machine-91: (16)
machine-100: (8)
machine-104: (32)
machine-105: (8)
machine-107: (8)
machine-110: (32)
machine-112: (8)
machine-114: (8)
machine-124: (8)
machine-127: (16)
machine-128: (8)
machine-129: (16)
machine-130: (32)
machine-145: (32)
machine-146: (8)
machine-149: (16)
machine-150: (32)
machine-151: (16)
machine-156: (16)
machine-157: (16)
machine-158: (16)
machine-159: (8)
machine-160: (8)
machine-163: (16)
machine-164: (8)
machine-166: (32)
machine-170: (16)
machine-172: (8)
machine-174: (32)
machine-175: (32)
machine-184: (8)
machine-185: (8)
machine-188: (8)
machine-192: (16)
machine-198: (8)
machine-199: (16)
machine-0: (32)
machine-5: (16)
machine-6: (32)
machine-10: (32)
machine-11: (16)
machine-15: (16)
machine-22: (8)
machine-23: (32)
machine-24: (8)
machine-30: (16)
machine-32: (16)
machine-33: (16)
machine-38: (16)
machine-42: (8)
machine-44: (8)
machine-48: (8)
machine-50: (8)
machine-54: (8)
machine-57: (32)
machine-59: (8)
machine-60: (8)
machine-61: (8)
machine-63: (16)
machine-65: (16)
machine-67: (16)
machine-69: (8)
machine-71: (32)
machine-82: (32)
machine-83: (32)
machine-85: (16)
machine-86: (16)
machine-87: (16)
machine-89: (8)
machine-93: (8)
machine-94: (16)
machine-97: (8)
machine-98: (8)
machine-99: (32)
machine-102: (32)
machine-103: (16)
machine-108: (16)
machine-115: (16)
machine-118: (32)
machine-119: (32)
machine-120: (16)
machine-125: (8)
machine-126: (8)
machine-131: (32)
machine-132: (32)
machine-135: (8)
machine-138: (8)
machine-139: (16)
machine-141: (16)
machine-144: (32)
machine-147: (32)
machine-148: (32)
machine-153: (32)
machine-154: (8)
machine-161: (8)
machine-171: (16)
machine-173: (16)
machine-176: (16)
machine-179: (16)
machine-181: (32)
machine-183: (16)
machine-189: (32)
machine-191: (16)
machine-193: (16)
machine-195: (32)
machine-196: (32)
machine-1: (32)
machine-2: (8)
machine-3: (32)
machine-4: (16)
machine-8: (32)
machine-9: (8)
machine-12: (8)
machine-17: (16)
machine-18: (16)
machine-19: (32)
machine-20: (32)
machine-27: (32)
machine-29: (8)
machine-31: (32)
machine-37: (8)
machine-41: (32)
machine-43: (8)
machine-45: (32)
machine-46: (8)
machine-47: (16)
machine-53: (8)
machine-58: (16)
machine-62: (16)
machine-66: (16)
machine-68: (8)
machine-70: (16)
machine-72: (32)
machine-74: (32)
machine-75: (32)
machine-76: (8)
machine-77: (8)
machine-79: (32)
machine-81: (8)
machine-84: (32)
machine-88: (32)
machine-92: (8)
machine-95: (8)
machine-96: (8)
machine-101: (8)
machine-106: (32)
machine-109: (8)
machine-111: (8)
machine-113: (32)
machine-116: (16)
machine-117: (8)
machine-121: (16)
machine-122: (8)
machine-123: (8)
machine-133: (8)
machine-134: (16)
machine-136: (32)
machine-137: (8)
machine-140: (32)
machine-142: (8)
machine-143: (16)
machine-152: (8)
machine-155: (32)
machine-162: (32)
machine-165: (16)
machine-167: (16)
machine-168: (16)
machine-169: (16)
machine-177: (16)
machine-178: (32)
machine-180: (8)
machine-182: (8)
machine-186: (8)
machine-187: (8)
machine-190: (8)
machine-194: (8)
machine-197: (16)
machine-21: 4 (16)
machine-16: 4 (32)
machine-14: 2 (32)
machine-13: 1 (16)
machine-7: 4 (16)
Occupation rate: 0%

######## Cpu Management ########
machine-25: (4)
machine-26: (4)
machine-28: (4)
machine-34: (4)
machine-35: (4)
machine-36: (4)
machine-39: (4)
machine-40: (4)
machine-49: (4)
machine-51: (4)
machine-52: (4)
machine-55: (4)
machine-56: (4)
machine-64: (4)
machine-73: (4)
machine-78: (4)
machine-80: (4)
machine-90: (4)
machine-91: (4)
machine-100: (4)
machine-104: (4)
machine-105: (4)
machine-107: (4)
machine-110: (4)
machine-112: (4)
machine-114: (4)
machine-124: (4)
machine-127: (4)
machine-128: (4)
machine-129: (4)
machine-130: (4)
machine-145: (4)
machine-146: (4)
machine-149: (4)
machine-150: (4)
machine-151: (4)
machine-156: (4)
machine-157: (4)
machine-158: (4)
machine-159: (4)
machine-160: (4)
machine-163: (4)
machine-164: (4)
machine-166: (4)
machine-170: (4)
machine-172: (4)
machine-174: (4)
machine-175: (4)
machine-184: (4)
machine-185: (4)
machine-188: (4)
machine-192: (4)
machine-198: (4)
machine-199: (4)
machine-0: (8)
machine-5: (8)
machine-6: (8)
machine-10: (8)
machine-11: (8)
machine-15: (8)
machine-22: (8)
machine-23: (8)
machine-24: (8)
machine-30: (8)
machine-32: (8)
machine-33: (8)
machine-38: (8)
machine-42: (8)
machine-44: (8)
machine-48: (8)
machine-50: (8)
machine-54: (8)
machine-57: (8)
machine-59: (8)
machine-60: (8)
machine-61: (8)
machine-63: (8)
machine-65: (8)
machine-67: (8)
machine-69: (8)
machine-71: (8)
machine-82: (8)
machine-83: (8)
machine-85: (8)
machine-86: (8)
machine-87: (8)
machine-89: (8)
machine-93: (8)
machine-94: (8)
machine-97: (8)
machine-98: (8)
machine-99: (8)
machine-102: (8)
machine-103: (8)
machine-108: (8)
machine-115: (8)
machine-118: (8)
machine-119: (8)
machine-120: (8)
machine-125: (8)
machine-126: (8)
machine-131: (8)
machine-132: (8)
machine-135: (8)
machine-138: (8)
machine-139: (8)
machine-141: (8)
machine-144: (8)
machine-147: (8)
machine-148: (8)
machine-153: (8)
machine-154: (8)
machine-161: (8)
machine-171: (8)
machine-173: (8)
machine-176: (8)
machine-179: (8)
machine-181: (8)
machine-183: (8)
machine-189: (8)
machine-191: (8)
machine-193: (8)
machine-195: (8)
machine-196: (8)
machine-1: (16)
machine-2: (16)
machine-3: (16)
machine-4: (16)
machine-8: (16)
machine-9: (16)
machine-12: (16)
machine-17: (16)
machine-18: (16)
machine-19: (16)
machine-20: (16)
machine-27: (16)
machine-29: (16)
machine-31: (16)
machine-37: (16)
machine-41: (16)
machine-43: (16)
machine-45: (16)
machine-46: (16)
machine-47: (16)
machine-53: (16)
machine-58: (16)
machine-62: (16)
machine-66: (16)
machine-68: (16)
machine-70: (16)
machine-72: (16)
machine-74: (16)
machine-75: (16)
machine-76: (16)
machine-77: (16)
machine-79: (16)
machine-81: (16)
machine-84: (16)
machine-88: (16)
machine-92: (16)
machine-95: (16)
machine-96: (16)
machine-101: (16)
machine-106: (16)
machine-109: (16)
machine-111: (16)
machine-113: (16)
machine-116: (16)
machine-117: (16)
machine-121: (16)
machine-122: (16)
machine-123: (16)
machine-133: (16)
machine-134: (16)
machine-136: (16)
machine-137: (16)
machine-140: (16)
machine-142: (16)
machine-143: (16)
machine-152: (16)
machine-155: (16)
machine-162: (16)
machine-165: (16)
machine-167: (16)
machine-168: (16)
machine-169: (16)
machine-177: (16)
machine-178: (16)
machine-180: (16)
machine-182: (16)
machine-186: (16)
machine-187: (16)
machine-190: (16)
machine-194: (16)
machine-197: (16)
machine-21: 1 (4)
machine-16: 2 (4)
machine-14: 3 (4)
machine-13: 3 (4)
machine-7: 3 (4)
Occupation rate: 1%

Name (cpuUsed/totalcpu,memoryused/totalmemory) - list VMs
machine-25 (0/4,0/16)  : []
machine-26 (0/4,0/32)  : []
machine-28 (0/4,0/32)  : []
machine-34 (0/4,0/16)  : []
machine-35 (0/4,0/16)  : []
machine-36 (0/4,0/16)  : []
machine-39 (0/4,0/16)  : []
machine-40 (0/4,0/8)  : []
machine-49 (0/4,0/16)  : []
machine-51 (0/4,0/16)  : []
machine-52 (0/4,0/16)  : []
machine-55 (0/4,0/16)  : []
machine-56 (0/4,0/16)  : []
machine-64 (0/4,0/16)  : []
machine-73 (0/4,0/16)  : []
machine-78 (0/4,0/16)  : []
machine-80 (0/4,0/32)  : []
machine-90 (0/4,0/16)  : []
machine-91 (0/4,0/16)  : []
machine-100 (0/4,0/8)  : []
machine-104 (0/4,0/32)  : []
machine-105 (0/4,0/8)  : []
machine-107 (0/4,0/8)  : []
machine-110 (0/4,0/32)  : []
machine-112 (0/4,0/8)  : []
machine-114 (0/4,0/8)  : []
machine-124 (0/4,0/8)  : []
machine-127 (0/4,0/16)  : []
machine-128 (0/4,0/8)  : []
machine-129 (0/4,0/16)  : []
machine-130 (0/4,0/32)  : []
machine-145 (0/4,0/32)  : []
machine-146 (0/4,0/8)  : []
machine-149 (0/4,0/16)  : []
machine-150 (0/4,0/32)  : []
machine-151 (0/4,0/16)  : []
machine-156 (0/4,0/16)  : []
machine-157 (0/4,0/16)  : []
machine-158 (0/4,0/16)  : []
machine-159 (0/4,0/8)  : []
machine-160 (0/4,0/8)  : []
machine-163 (0/4,0/16)  : []
machine-164 (0/4,0/8)  : []
machine-166 (0/4,0/32)  : []
machine-170 (0/4,0/16)  : []
machine-172 (0/4,0/8)  : []
machine-174 (0/4,0/32)  : []
machine-175 (0/4,0/32)  : []
machine-184 (0/4,0/8)  : []
machine-185 (0/4,0/8)  : []
machine-188 (0/4,0/8)  : []
machine-192 (0/4,0/16)  : []
machine-198 (0/4,0/8)  : []
machine-199 (0/4,0/16)  : []
machine-0 (0/8,0/32)  : []
machine-5 (0/8,0/16)  : []
machine-6 (0/8,0/32)  : []
machine-10 (0/8,0/32)  : []
machine-11 (0/8,0/16)  : []
machine-15 (0/8,0/16)  : []
machine-22 (0/8,0/8)  : []
machine-23 (0/8,0/32)  : []
machine-24 (0/8,0/8)  : []
machine-30 (0/8,0/16)  : []
machine-32 (0/8,0/16)  : []
machine-33 (0/8,0/16)  : []
machine-38 (0/8,0/16)  : []
machine-42 (0/8,0/8)  : []
machine-44 (0/8,0/8)  : []
machine-48 (0/8,0/8)  : []
machine-50 (0/8,0/8)  : []
machine-54 (0/8,0/8)  : []
machine-57 (0/8,0/32)  : []
machine-59 (0/8,0/8)  : []
machine-60 (0/8,0/8)  : []
machine-61 (0/8,0/8)  : []
machine-63 (0/8,0/16)  : []
machine-65 (0/8,0/16)  : []
machine-67 (0/8,0/16)  : []
machine-69 (0/8,0/8)  : []
machine-71 (0/8,0/32)  : []
machine-82 (0/8,0/32)  : []
machine-83 (0/8,0/32)  : []
machine-85 (0/8,0/16)  : []
machine-86 (0/8,0/16)  : []
machine-87 (0/8,0/16)  : []
machine-89 (0/8,0/8)  : []
machine-93 (0/8,0/8)  : []
machine-94 (0/8,0/16)  : []
machine-97 (0/8,0/8)  : []
machine-98 (0/8,0/8)  : []
machine-99 (0/8,0/32)  : []
machine-102 (0/8,0/32)  : []
machine-103 (0/8,0/16)  : []
machine-108 (0/8,0/16)  : []
machine-115 (0/8,0/16)  : []
machine-118 (0/8,0/32)  : []
machine-119 (0/8,0/32)  : []
machine-120 (0/8,0/16)  : []
machine-125 (0/8,0/8)  : []
machine-126 (0/8,0/8)  : []
machine-131 (0/8,0/32)  : []
machine-132 (0/8,0/32)  : []
machine-135 (0/8,0/8)  : []
machine-138 (0/8,0/8)  : []
machine-139 (0/8,0/16)  : []
machine-141 (0/8,0/16)  : []
machine-144 (0/8,0/32)  : []
machine-147 (0/8,0/32)  : []
machine-148 (0/8,0/32)  : []
machine-153 (0/8,0/32)  : []
machine-154 (0/8,0/8)  : []
machine-161 (0/8,0/8)  : []
machine-171 (0/8,0/16)  : []
machine-173 (0/8,0/16)  : []
machine-176 (0/8,0/16)  : []
machine-179 (0/8,0/16)  : []
machine-181 (0/8,0/32)  : []
machine-183 (0/8,0/16)  : []
machine-189 (0/8,0/32)  : []
machine-191 (0/8,0/16)  : []
machine-193 (0/8,0/16)  : []
machine-195 (0/8,0/32)  : []
machine-196 (0/8,0/32)  : []
machine-1 (0/16,0/32)  : []
machine-2 (0/16,0/8)  : []
machine-3 (0/16,0/32)  : []
machine-4 (0/16,0/16)  : []
machine-8 (0/16,0/32)  : []
machine-9 (0/16,0/8)  : []
machine-12 (0/16,0/8)  : []
machine-17 (0/16,0/16)  : []
machine-18 (0/16,0/16)  : []
machine-19 (0/16,0/32)  : []
machine-20 (0/16,0/32)  : []
machine-27 (0/16,0/32)  : []
machine-29 (0/16,0/8)  : []
machine-31 (0/16,0/32)  : []
machine-37 (0/16,0/8)  : []
machine-41 (0/16,0/32)  : []
machine-43 (0/16,0/8)  : []
machine-45 (0/16,0/32)  : []
machine-46 (0/16,0/8)  : []
machine-47 (0/16,0/16)  : []
machine-53 (0/16,0/8)  : []
machine-58 (0/16,0/16)  : []
machine-62 (0/16,0/16)  : []
machine-66 (0/16,0/16)  : []
machine-68 (0/16,0/8)  : []
machine-70 (0/16,0/16)  : []
machine-72 (0/16,0/32)  : []
machine-74 (0/16,0/32)  : []
machine-75 (0/16,0/32)  : []
machine-76 (0/16,0/8)  : []
machine-77 (0/16,0/8)  : []
machine-79 (0/16,0/32)  : []
machine-81 (0/16,0/8)  : []
machine-84 (0/16,0/32)  : []
machine-88 (0/16,0/32)  : []
machine-92 (0/16,0/8)  : []
machine-95 (0/16,0/8)  : []
machine-96 (0/16,0/8)  : []
machine-101 (0/16,0/8)  : []
machine-106 (0/16,0/32)  : []
machine-109 (0/16,0/8)  : []
machine-111 (0/16,0/8)  : []
machine-113 (0/16,0/32)  : []
machine-116 (0/16,0/16)  : []
machine-117 (0/16,0/8)  : []
machine-121 (0/16,0/16)  : []
machine-122 (0/16,0/8)  : []
machine-123 (0/16,0/8)  : []
machine-133 (0/16,0/8)  : []
machine-134 (0/16,0/16)  : []
machine-136 (0/16,0/32)  : []
machine-137 (0/16,0/8)  : []
machine-140 (0/16,0/32)  : []
machine-142 (0/16,0/8)  : []
machine-143 (0/16,0/16)  : []
machine-152 (0/16,0/8)  : []
machine-155 (0/16,0/32)  : []
machine-162 (0/16,0/32)  : []
machine-165 (0/16,0/16)  : []
machine-167 (0/16,0/16)  : []
machine-168 (0/16,0/16)  : []
machine-169 (0/16,0/16)  : []
machine-177 (0/16,0/16)  : []
machine-178 (0/16,0/32)  : []
machine-180 (0/16,0/8)  : []
machine-182 (0/16,0/8)  : []
machine-186 (0/16,0/8)  : []
machine-187 (0/16,0/8)  : []
machine-190 (0/16,0/8)  : []
machine-194 (0/16,0/8)  : []
machine-197 (0/16,0/16)  : []
machine-21 (1/4,4/16)  : [vm3(1,4)]
machine-16 (2/4,4/32)  : [vm0(2,4)]
machine-14 (3/4,2/32)  : [vm1(3,2)]
machine-13 (3/4,1/16)  : [vm2(3,1)]
machine-7 (3/4,4/16)  : [vm4(3,4)]

 Machine Energy :  - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 162 - 175 - 187 - 187 - 187
 Energy : 898


Welcome to the constraint world ...


#################################
######### Loops 1 ###############
#################################

###### Memory Management #######
machine-7: 4 4 4 2 1 (16)
machine-13: (16)
machine-14: (32)
machine-16: (32)
machine-21: (16)
machine-199: (16)
machine-198: (8)
machine-192: (16)
machine-188: (8)
machine-185: (8)
machine-184: (8)
machine-175: (32)
machine-174: (32)
machine-172: (8)
machine-170: (16)
machine-166: (32)
machine-164: (8)
machine-163: (16)
machine-160: (8)
machine-159: (8)
machine-158: (16)
machine-157: (16)
machine-156: (16)
machine-151: (16)
machine-150: (32)
machine-149: (16)
machine-146: (8)
machine-145: (32)
machine-130: (32)
machine-129: (16)
machine-128: (8)
machine-127: (16)
machine-124: (8)
machine-114: (8)
machine-112: (8)
machine-110: (32)
machine-107: (8)
machine-105: (8)
machine-104: (32)
machine-100: (8)
machine-91: (16)
machine-90: (16)
machine-80: (32)
machine-78: (16)
machine-73: (16)
machine-64: (16)
machine-56: (16)
machine-55: (16)
machine-52: (16)
machine-51: (16)
machine-49: (16)
machine-40: (8)
machine-39: (16)
machine-36: (16)
machine-35: (16)
machine-34: (16)
machine-28: (32)
machine-26: (32)
machine-25: (16)
machine-196: (32)
machine-195: (32)
machine-193: (16)
machine-191: (16)
machine-189: (32)
machine-183: (16)
machine-181: (32)
machine-179: (16)
machine-176: (16)
machine-173: (16)
machine-171: (16)
machine-161: (8)
machine-154: (8)
machine-153: (32)
machine-148: (32)
machine-147: (32)
machine-144: (32)
machine-141: (16)
machine-139: (16)
machine-138: (8)
machine-135: (8)
machine-132: (32)
machine-131: (32)
machine-126: (8)
machine-125: (8)
machine-120: (16)
machine-119: (32)
machine-118: (32)
machine-115: (16)
machine-108: (16)
machine-103: (16)
machine-102: (32)
machine-99: (32)
machine-98: (8)
machine-97: (8)
machine-94: (16)
machine-93: (8)
machine-89: (8)
machine-87: (16)
machine-86: (16)
machine-85: (16)
machine-83: (32)
machine-82: (32)
machine-71: (32)
machine-69: (8)
machine-67: (16)
machine-65: (16)
machine-63: (16)
machine-61: (8)
machine-60: (8)
machine-59: (8)
machine-57: (32)
machine-54: (8)
machine-50: (8)
machine-48: (8)
machine-44: (8)
machine-42: (8)
machine-38: (16)
machine-33: (16)
machine-32: (16)
machine-30: (16)
machine-24: (8)
machine-23: (32)
machine-22: (8)
machine-15: (16)
machine-11: (16)
machine-10: (32)
machine-6: (32)
machine-5: (16)
machine-0: (32)
machine-197: (16)
machine-194: (8)
machine-190: (8)
machine-187: (8)
machine-186: (8)
machine-182: (8)
machine-180: (8)
machine-178: (32)
machine-177: (16)
machine-169: (16)
machine-168: (16)
machine-167: (16)
machine-165: (16)
machine-162: (32)
machine-155: (32)
machine-152: (8)
machine-143: (16)
machine-142: (8)
machine-140: (32)
machine-137: (8)
machine-136: (32)
machine-134: (16)
machine-133: (8)
machine-123: (8)
machine-122: (8)
machine-121: (16)
machine-117: (8)
machine-116: (16)
machine-113: (32)
machine-111: (8)
machine-109: (8)
machine-106: (32)
machine-101: (8)
machine-96: (8)
machine-95: (8)
machine-92: (8)
machine-88: (32)
machine-84: (32)
machine-81: (8)
machine-79: (32)
machine-77: (8)
machine-76: (8)
machine-75: (32)
machine-74: (32)
machine-72: (32)
machine-70: (16)
machine-68: (8)
machine-66: (16)
machine-62: (16)
machine-58: (16)
machine-53: (8)
machine-47: (16)
machine-46: (8)
machine-45: (32)
machine-43: (8)
machine-41: (32)
machine-37: (8)
machine-31: (32)
machine-29: (8)
machine-27: (32)
machine-20: (32)
machine-19: (32)
machine-18: (16)
machine-17: (16)
machine-12: (8)
machine-9: (8)
machine-8: (32)
machine-4: (16)
machine-3: (32)
machine-2: (8)
machine-1: (32)
Occupation rate: 0%

######## Cpu Management ########
machine-7: 3 2 1 3 3 (4)
machine-13: (4)
machine-14: (4)
machine-16: (4)
machine-21: (4)
machine-199: (4)
machine-198: (4)
machine-192: (4)
machine-188: (4)
machine-185: (4)
machine-184: (4)
machine-175: (4)
machine-174: (4)
machine-172: (4)
machine-170: (4)
machine-166: (4)
machine-164: (4)
machine-163: (4)
machine-160: (4)
machine-159: (4)
machine-158: (4)
machine-157: (4)
machine-156: (4)
machine-151: (4)
machine-150: (4)
machine-149: (4)
machine-146: (4)
machine-145: (4)
machine-130: (4)
machine-129: (4)
machine-128: (4)
machine-127: (4)
machine-124: (4)
machine-114: (4)
machine-112: (4)
machine-110: (4)
machine-107: (4)
machine-105: (4)
machine-104: (4)
machine-100: (4)
machine-91: (4)
machine-90: (4)
machine-80: (4)
machine-78: (4)
machine-73: (4)
machine-64: (4)
machine-56: (4)
machine-55: (4)
machine-52: (4)
machine-51: (4)
machine-49: (4)
machine-40: (4)
machine-39: (4)
machine-36: (4)
machine-35: (4)
machine-34: (4)
machine-28: (4)
machine-26: (4)
machine-25: (4)
machine-196: (8)
machine-195: (8)
machine-193: (8)
machine-191: (8)
machine-189: (8)
machine-183: (8)
machine-181: (8)
machine-179: (8)
machine-176: (8)
machine-173: (8)
machine-171: (8)
machine-161: (8)
machine-154: (8)
machine-153: (8)
machine-148: (8)
machine-147: (8)
machine-144: (8)
machine-141: (8)
machine-139: (8)
machine-138: (8)
machine-135: (8)
machine-132: (8)
machine-131: (8)
machine-126: (8)
machine-125: (8)
machine-120: (8)
machine-119: (8)
machine-118: (8)
machine-115: (8)
machine-108: (8)
machine-103: (8)
machine-102: (8)
machine-99: (8)
machine-98: (8)
machine-97: (8)
machine-94: (8)
machine-93: (8)
machine-89: (8)
machine-87: (8)
machine-86: (8)
machine-85: (8)
machine-83: (8)
machine-82: (8)
machine-71: (8)
machine-69: (8)
machine-67: (8)
machine-65: (8)
machine-63: (8)
machine-61: (8)
machine-60: (8)
machine-59: (8)
machine-57: (8)
machine-54: (8)
machine-50: (8)
machine-48: (8)
machine-44: (8)
machine-42: (8)
machine-38: (8)
machine-33: (8)
machine-32: (8)
machine-30: (8)
machine-24: (8)
machine-23: (8)
machine-22: (8)
machine-15: (8)
machine-11: (8)
machine-10: (8)
machine-6: (8)
machine-5: (8)
machine-0: (8)
machine-197: (16)
machine-194: (16)
machine-190: (16)
machine-187: (16)
machine-186: (16)
machine-182: (16)
machine-180: (16)
machine-178: (16)
machine-177: (16)
machine-169: (16)
machine-168: (16)
machine-167: (16)
machine-165: (16)
machine-162: (16)
machine-155: (16)
machine-152: (16)
machine-143: (16)
machine-142: (16)
machine-140: (16)
machine-137: (16)
machine-136: (16)
machine-134: (16)
machine-133: (16)
machine-123: (16)
machine-122: (16)
machine-121: (16)
machine-117: (16)
machine-116: (16)
machine-113: (16)
machine-111: (16)
machine-109: (16)
machine-106: (16)
machine-101: (16)
machine-96: (16)
machine-95: (16)
machine-92: (16)
machine-88: (16)
machine-84: (16)
machine-81: (16)
machine-79: (16)
machine-77: (16)
machine-76: (16)
machine-75: (16)
machine-74: (16)
machine-72: (16)
machine-70: (16)
machine-68: (16)
machine-66: (16)
machine-62: (16)
machine-58: (16)
machine-53: (16)
machine-47: (16)
machine-46: (16)
machine-45: (16)
machine-43: (16)
machine-41: (16)
machine-37: (16)
machine-31: (16)
machine-29: (16)
machine-27: (16)
machine-20: (16)
machine-19: (16)
machine-18: (16)
machine-17: (16)
machine-12: (16)
machine-9: (16)
machine-8: (16)
machine-4: (16)
machine-3: (16)
machine-2: (16)
machine-1: (16)
Occupation rate: 1%

Name (cpuUsed/totalcpu,memoryused/totalmemory) - list VMs
machine-7 (12/4,15/16)  : [vm4(3,4), vm0(2,4), vm3(1,4), vm1(3,2), vm2(3,1)]
machine-13 (0/4,0/16)  : []
machine-14 (0/4,0/32)  : []
machine-16 (0/4,0/32)  : []
machine-21 (0/4,0/16)  : []
machine-199 (0/4,0/16)  : []
machine-198 (0/4,0/8)  : []
machine-192 (0/4,0/16)  : []
machine-188 (0/4,0/8)  : []
machine-185 (0/4,0/8)  : []
machine-184 (0/4,0/8)  : []
machine-175 (0/4,0/32)  : []
machine-174 (0/4,0/32)  : []
machine-172 (0/4,0/8)  : []
machine-170 (0/4,0/16)  : []
machine-166 (0/4,0/32)  : []
machine-164 (0/4,0/8)  : []
machine-163 (0/4,0/16)  : []
machine-160 (0/4,0/8)  : []
machine-159 (0/4,0/8)  : []
machine-158 (0/4,0/16)  : []
machine-157 (0/4,0/16)  : []
machine-156 (0/4,0/16)  : []
machine-151 (0/4,0/16)  : []
machine-150 (0/4,0/32)  : []
machine-149 (0/4,0/16)  : []
machine-146 (0/4,0/8)  : []
machine-145 (0/4,0/32)  : []
machine-130 (0/4,0/32)  : []
machine-129 (0/4,0/16)  : []
machine-128 (0/4,0/8)  : []
machine-127 (0/4,0/16)  : []
machine-124 (0/4,0/8)  : []
machine-114 (0/4,0/8)  : []
machine-112 (0/4,0/8)  : []
machine-110 (0/4,0/32)  : []
machine-107 (0/4,0/8)  : []
machine-105 (0/4,0/8)  : []
machine-104 (0/4,0/32)  : []
machine-100 (0/4,0/8)  : []
machine-91 (0/4,0/16)  : []
machine-90 (0/4,0/16)  : []
machine-80 (0/4,0/32)  : []
machine-78 (0/4,0/16)  : []
machine-73 (0/4,0/16)  : []
machine-64 (0/4,0/16)  : []
machine-56 (0/4,0/16)  : []
machine-55 (0/4,0/16)  : []
machine-52 (0/4,0/16)  : []
machine-51 (0/4,0/16)  : []
machine-49 (0/4,0/16)  : []
machine-40 (0/4,0/8)  : []
machine-39 (0/4,0/16)  : []
machine-36 (0/4,0/16)  : []
machine-35 (0/4,0/16)  : []
machine-34 (0/4,0/16)  : []
machine-28 (0/4,0/32)  : []
machine-26 (0/4,0/32)  : []
machine-25 (0/4,0/16)  : []
machine-196 (0/8,0/32)  : []
machine-195 (0/8,0/32)  : []
machine-193 (0/8,0/16)  : []
machine-191 (0/8,0/16)  : []
machine-189 (0/8,0/32)  : []
machine-183 (0/8,0/16)  : []
machine-181 (0/8,0/32)  : []
machine-179 (0/8,0/16)  : []
machine-176 (0/8,0/16)  : []
machine-173 (0/8,0/16)  : []
machine-171 (0/8,0/16)  : []
machine-161 (0/8,0/8)  : []
machine-154 (0/8,0/8)  : []
machine-153 (0/8,0/32)  : []
machine-148 (0/8,0/32)  : []
machine-147 (0/8,0/32)  : []
machine-144 (0/8,0/32)  : []
machine-141 (0/8,0/16)  : []
machine-139 (0/8,0/16)  : []
machine-138 (0/8,0/8)  : []
machine-135 (0/8,0/8)  : []
machine-132 (0/8,0/32)  : []
machine-131 (0/8,0/32)  : []
machine-126 (0/8,0/8)  : []
machine-125 (0/8,0/8)  : []
machine-120 (0/8,0/16)  : []
machine-119 (0/8,0/32)  : []
machine-118 (0/8,0/32)  : []
machine-115 (0/8,0/16)  : []
machine-108 (0/8,0/16)  : []
machine-103 (0/8,0/16)  : []
machine-102 (0/8,0/32)  : []
machine-99 (0/8,0/32)  : []
machine-98 (0/8,0/8)  : []
machine-97 (0/8,0/8)  : []
machine-94 (0/8,0/16)  : []
machine-93 (0/8,0/8)  : []
machine-89 (0/8,0/8)  : []
machine-87 (0/8,0/16)  : []
machine-86 (0/8,0/16)  : []
machine-85 (0/8,0/16)  : []
machine-83 (0/8,0/32)  : []
machine-82 (0/8,0/32)  : []
machine-71 (0/8,0/32)  : []
machine-69 (0/8,0/8)  : []
machine-67 (0/8,0/16)  : []
machine-65 (0/8,0/16)  : []
machine-63 (0/8,0/16)  : []
machine-61 (0/8,0/8)  : []
machine-60 (0/8,0/8)  : []
machine-59 (0/8,0/8)  : []
machine-57 (0/8,0/32)  : []
machine-54 (0/8,0/8)  : []
machine-50 (0/8,0/8)  : []
machine-48 (0/8,0/8)  : []
machine-44 (0/8,0/8)  : []
machine-42 (0/8,0/8)  : []
machine-38 (0/8,0/16)  : []
machine-33 (0/8,0/16)  : []
machine-32 (0/8,0/16)  : []
machine-30 (0/8,0/16)  : []
machine-24 (0/8,0/8)  : []
machine-23 (0/8,0/32)  : []
machine-22 (0/8,0/8)  : []
machine-15 (0/8,0/16)  : []
machine-11 (0/8,0/16)  : []
machine-10 (0/8,0/32)  : []
machine-6 (0/8,0/32)  : []
machine-5 (0/8,0/16)  : []
machine-0 (0/8,0/32)  : []
machine-197 (0/16,0/16)  : []
machine-194 (0/16,0/8)  : []
machine-190 (0/16,0/8)  : []
machine-187 (0/16,0/8)  : []
machine-186 (0/16,0/8)  : []
machine-182 (0/16,0/8)  : []
machine-180 (0/16,0/8)  : []
machine-178 (0/16,0/32)  : []
machine-177 (0/16,0/16)  : []
machine-169 (0/16,0/16)  : []
machine-168 (0/16,0/16)  : []
machine-167 (0/16,0/16)  : []
machine-165 (0/16,0/16)  : []
machine-162 (0/16,0/32)  : []
machine-155 (0/16,0/32)  : []
machine-152 (0/16,0/8)  : []
machine-143 (0/16,0/16)  : []
machine-142 (0/16,0/8)  : []
machine-140 (0/16,0/32)  : []
machine-137 (0/16,0/8)  : []
machine-136 (0/16,0/32)  : []
machine-134 (0/16,0/16)  : []
machine-133 (0/16,0/8)  : []
machine-123 (0/16,0/8)  : []
machine-122 (0/16,0/8)  : []
machine-121 (0/16,0/16)  : []
machine-117 (0/16,0/8)  : []
machine-116 (0/16,0/16)  : []
machine-113 (0/16,0/32)  : []
machine-111 (0/16,0/8)  : []
machine-109 (0/16,0/8)  : []
machine-106 (0/16,0/32)  : []
machine-101 (0/16,0/8)  : []
machine-96 (0/16,0/8)  : []
machine-95 (0/16,0/8)  : []
machine-92 (0/16,0/8)  : []
machine-88 (0/16,0/32)  : []
machine-84 (0/16,0/32)  : []
machine-81 (0/16,0/8)  : []
machine-79 (0/16,0/32)  : []
machine-77 (0/16,0/8)  : []
machine-76 (0/16,0/8)  : []
machine-75 (0/16,0/32)  : []
machine-74 (0/16,0/32)  : []
machine-72 (0/16,0/32)  : []
machine-70 (0/16,0/16)  : []
machine-68 (0/16,0/8)  : []
machine-66 (0/16,0/16)  : []
machine-62 (0/16,0/16)  : []
machine-58 (0/16,0/16)  : []
machine-53 (0/16,0/8)  : []
machine-47 (0/16,0/16)  : []
machine-46 (0/16,0/8)  : []
machine-45 (0/16,0/32)  : []
machine-43 (0/16,0/8)  : []
machine-41 (0/16,0/32)  : []
machine-37 (0/16,0/8)  : []
machine-31 (0/16,0/32)  : []
machine-29 (0/16,0/8)  : []
machine-27 (0/16,0/32)  : []
machine-20 (0/16,0/32)  : []
machine-19 (0/16,0/32)  : []
machine-18 (0/16,0/16)  : []
machine-17 (0/16,0/16)  : []
machine-12 (0/16,0/8)  : []
machine-9 (0/16,0/8)  : []
machine-8 (0/16,0/32)  : []
machine-4 (0/16,0/16)  : []
machine-3 (0/16,0/32)  : []
machine-2 (0/16,0/8)  : []
machine-1 (0/16,0/32)  : []

 Machine Energy :  - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 0 - 200 - 200 - 200 - 200
 Energy : 800

Computation time: 463
Solving times: [463]
Mean: 463
